---
- hosts: 192.168.56.11
  become: yes
  tasks:
    - name: Install httpd packages
      package:
        name: httpd
        state: latest
    - name: Copy index.html file
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
      notify:
        - restart httpd
    - name: Start and enabled httpd 
      service:
        name: httpd
        state : restarted
        enabled: yes
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
