---
- hosts: all
  become: yes
  tasks: 
    - name: Get java from URL
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
        dest: /root
        mode: 0440
