---
- hosts: all
  become: yes
  
  vars:
      packages:
        - httpd
        - gcc
  tasks:
    - name: install packages
      package:
        name: "{{item}}"
        state: present
      with_items: "{{ packages }}"
